spring.cloud.stream:
  function:
    definition: domainConsumer
  bindings:
    domainConsumer-in-0:
      destination: active.web-domains
      kafka:
    bindings:
      domainConsumer-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      binder:
      brokers:
        - localhost:9091
        - localhost:9092

